<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomerService.Application\CustomerService.Application.csproj" />
    <ProjectReference Include="..\CustomerServiceDomain\CustomerService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Authintication\" />
  </ItemGroup>

</Project>
